### ISSUE TITLE
Inconsistent Escaping

### ISSUE THREAD

**Issue by luigi-asprino** [SPARQL-Anything/sparql.anything#246]
Percent escaper used by Triplifier.toSafeURIString is badly initialised since it escapes safe URI characters like "-", "_" etc.

**Comment by luigi-asprino** [comment]
With 097b944 "-", "_", "." and "~" are considered safe (this complies with https://www.ietf.org/rfc/rfc3986.txt)

**Comment by luigi-asprino** [comment]
Closing via 097b94401c65e2fcc7ce222ba6427b0d7383bbf5

**Comment by enridaga** [comment]
Is this the same as #113 ?

**Comment by luigi-asprino** [comment]
Of course it is related to #113, but I think that #113 is a broader discussion on how to make pretty local names.
Here, I've just made the triplification of JSON consistent with others triplifiers.
Before 095b944, a field like "first_name" was transformed into "first%5Fname" by the JSON triplified.

**Comment by enridaga** [comment]
Indeed, #113 is broader but I think most of the issue was on the configuration of the escape -- thank you for spotting that! 
It looks like the change applies to any triplifier since that method is used from within the triple builder not the triplifiers. Which is a good thing :)

We need to mention that in the next release notes since this change may affect existing queries.
