### ISSUE TITLE
prefixes of XML attributes are not resolved

### ISSUE THREAD

**Issue by mielvds** [SPARQL-Anything/sparql.anything#322]
Hi there! SPARQL-Anything tries to reuse the XML namespaces as much as possible. However, it seems that this only the case for elements; attributes are turned into literals. Isn't that unintuitive?

Example: 

- input: `<premis:premis xsi:type="premis:intellectualEntity">` 
- output: `[] a premis:premis; xsi:type  "premis:intellectualEntity"`
- expected: `[] a premis:premis; xsi:type premis:intellectualEntity`

**Comment by enridaga** [comment]
Hi Miel! I see your point. The issue is that we cannot make assumptions about attribute values in XML without inspecting the schema, so the safe way is to consider them as literals. 
If the XML is bound with a Schema and we support XSD schema resolution, it could be possible to know that a given attribute value is supposed to be a QName, but it would still be problematic to generalise (any string is an IRI anyway, colons don't make it safe to distinguish prefixed vs non-prefixed URIs).
This is a typical issue with XML; see, for example, https://stackoverflow.com/a/50236609/1035608 .

The safer thing is to handle these cases in your mappings (I guess you will transform the data anyway). If you still want an IRI from that string, you can always `BIND( fx:entity ( "premis:intellectualEntity") as ?type )` assuming `premis:` is in the set of ns declarations.

My two cents

**Comment by mielvds** [comment]
That makes total sense. Thanks @enridaga !

**Comment by mielvds** [comment]
btw, I would suggest adding  a summary of your answer to [the docs ](https://sparql-anything.readthedocs.io/en/latest/formats/XML/) where it says "SPARQL Anything reuses namespaces declared ..."
