### ISSUE TITLE
Apache Jena function `apf:strSplit` not working within the service clause

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#330]
This issue emerged while tackling #329 -- it appears that moving the call outside the SERVICE clause fixed the problem.

See https://github.com/SPARQL-Anything/sparql.anything/issues/329#issuecomment-1397101722

**Comment by enridaga** [comment]
Does the FX executor register APF functions?

**Comment by luigi-asprino** [comment]
My understanding of the thing is the following. 
First of all, let me say that I don't fully understand what Jena does.
However, I was able to track the execution and I have a general idea of the workflow.
Suppose having this query

```
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  apf:  <http://jena.apache.org/ARQ/property#>

SELECT  ?a
WHERE
  { ?s    rdf:_1        ?o .
    ?a    apf:strSplit  ( ?o ";" )
  }
```

This translates in Algebra as

```
(project (?a)
  (bgp
    (triple ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1> ?o)
    (triple ?a <http://jena.apache.org/ARQ/property#strSplit> ??0)
    (triple ??0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> ?o)
    (triple ??0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> ??1)
    (triple ??1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#first> ";")
    (triple ??1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> <http://www.w3.org/1999/02/22-rdf-syntax-ns#nil>)
  ))
```

The Jena optimiser transforms the OpBGP into 

```
(propfunc <http://jena.apache.org/ARQ/property#strSplit>
  ?a (?o ";")
  (bgp (triple ?s <http://www.w3.org/1999/02/22-rdf-syntax-ns#_1> ?o)))
```

via the `TransformPropertyFunction.transform()` method.
This does not seem to happen for the BGPs inside the SERVICE clause (perhaps because the optimisation of the operations is supposed to be the responsibility of the remote endpoint (?)).

As a result, to make the Apache Jena functions work inside the service clause we just need to transform the OpBGP at some point. This would turn the OpBGP into a OpPropFunc and will be evaluated as exepected.

**Comment by luigi-asprino** [comment]
By the way, if the operations within the service are not optimised maybe the execution is not optimal.. maybe we could consider invoking the optimiser in  FXOpExecutor.execute(OpService).

**Comment by enridaga** [comment]
> By the way, if the operations within the service are not optimised maybe the execution is not optimal.. maybe we could consider invoking the optimiser in FXOpExecutor.execute(OpService).

Excellent point; I am opening an issue for that.
