### ISSUE TITLE
fails on empty folder in zip

### ISSUE THREAD

**Issue by VladimirAlexiev** [SPARQL-Anything/sparql.anything#334]
This script
```sparql
# rdfize an archive (zip) of files.
# parameter values:
# -v zip: zip filename or URL
# -v file: file regexp pattern (default ~.*~)
# sparql-anything -q ../rdfize-zip.sparql -v zip=graphql-2023-01-24.zip > raw-rdf.ttl
# See https://sparql-anything.readthedocs.io/en/latest/Configuration/#from-archive

prefix bsdd: <http://bsdd.buildingsmart.org/def#>
prefix xyz:  <http://sparql.xyz/facade-x/data/>
prefix fx:   <http://sparql.xyz/facade-x/ns/>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:  <http://www.w3.org/2001/XMLSchema#>

construct {
  ?s ?p ?o
} where {
  service <x-sparql-anything:> {
    bind(coalesce(?__file,".*") as ?pattern)
    fx:properties fx:location ?_zip.
    fx:properties fx:archive.matches ?pattern.
    [] fx:anySlot ?file
    service <x-sparql-anything:media-type=application/json> {
      bind(str(bsdd:) as ?bsdd)
      fx:properties fx:namespace ?bsdd.
      fx:properties fx:location ?file.
      fx:properties fx:from-archive ?_zip.
      fx:properties fx:use-rdfs-member true.
      ?s ?p ?o
    }
  }
}
```
fails on an empty folder inside the zip:
```
ERROR com.github.sparqlanything.cli.SPARQLAnything - Iteration 1 failed with error: 
java.io.IOException: java.io.FileNotFoundException: 
tmp\9c7edbb4c5428e0901712bba87769bf1\domains\csi_omniclass-1 (Access is denied)
```

**Comment by luigi-asprino** [comment]
Hi,

thanks for reporting the issue which made me go deeper into the SPARQL execution.
It took me a while to understand what was wrong.
I try to explain the problem here.

The query evaluator executes the external service first (hence, it creates the dataset graph according to Facade-X zip triplifier), and evaluates the magic properties fx:anySlot (which binds `?file` to the files/directories of the archive). 
Then, the generated dataset is used as execution context for evaluating the inner service.
So far so expected.
However, the bindings of the `?file` variable are not used as input to evaluate the inner service (the join of the variable ?file of the two service clauses is executed later).
This causes that `?file` to be bound to fx:root when evaluating the inner service and the tool tries to access the location fx:root within the zip (which does not exist => IOException).
To avoid this,  I have made sure that when a directory or a non-existing file is given as location the ResourceManager returns an empty InputStream which is triplified as `[ rdf:type  fx:root ] .`

Not sure if this is the best way to go, but it works.
Suggestions welcome.

This also explains and addresses #335

**Comment by enridaga** [comment]
The query had two problems:

- The pattern is indeed matching directories, which would break the second service clause expecting a JSON file. This can be solved with a regex that matches files only (although it would be nice to have the engine skipping directories as default)
- The order of service clauses results in an algebra where the two services are not in the right order. This is tricky, and we should probably extend the documentation to include some examples of how better chain SERVICE clauses.

From experience, when we concatenate SERVICE clauses, the order should be from the inner to the outer, as in the following case:

```sparql
prefix bsdd: <http://bsdd.buildingsmart.org/def#>
prefix xyz:  <http://sparql.xyz/facade-x/data/>
prefix fx:   <http://sparql.xyz/facade-x/ns/>
prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix xsd:  <http://www.w3.org/2001/XMLSchema#>

construct {
  ?s ?p ?o
} where {
	# Step 2
    service <x-sparql-anything:media-type=application/json> {
	  # Step 1 inside!!!
	  service <x-sparql-anything:> {
	      bind(coalesce(?__file,".*") as ?pattern)
	      fx:properties fx:location "./issue334.tar" .
	      fx:properties fx:archive.matches ".*\\.[^\\.]*$" .
	      [] fx:anySlot ?file
  	  }
      bind(str(bsdd:) as ?bsdd)
      fx:properties fx:namespace ?bsdd.
      fx:properties fx:location ?file.
      fx:properties fx:from-archive "./issue334.tar".
      fx:properties fx:use-rdfs-member true.
      ?s ?p ?o
    }
}
```

The above seems to work well with v0.8.1, see also https://github.com/SPARQL-Anything/sandbox/tree/main/issue334

**Comment by luigi-asprino** [comment]
Thanks Enrico.

I was too eager to blame SPARQL Anything.

In https://github.com/SPARQL-Anything/sparql.anything/commit/36f7e6e2320c8d4ec880bd2fe6e6faf4b06e23bf I removed previous changes.

**Comment by luigi-asprino** [comment]
I think we can close this
