### ISSUE TITLE
Specifying Named Graphs in a Local Spreadsheet

### ISSUE THREAD

**Issue by svirgilgood** [SPARQL-Anything/sparql.anything#351]
In the example for working with spreadsheets, it is easy to specify the sheet with the named graph:
```sparql
SELECT ?s ?p ?o 
WHERE {
  SERVICE <x-sparql-anything:location=https://sparql-anything.cc/examples/Book1.xlsx>
  { GRAPH <https://sparql-anything.cc/examples/Book1.xlsx#Sheet2> {
       ?s ?p ?o . 
    }
  }
}
``` 
Will return only the triples that are constructed from sheet2 in the work book. However if you download the file locally, you can not specify the named graph. 
```sparql 

SELECT ?s ?p ?o 
WHERE {
   SERVICE <x-sparql-anything:location=file:///home/user/Documents/Book1.xlsx> 
   { GRAPH <file:///home/user/Documents/Book1.xlsx#Sheet2> {
      ?s ?p ?o .
      }
   }
}
``` 
This query will return no results. And if you run a query for all of the named graphs in the book, the named graph for this sheet will be: `<file:/home/user/Documents/Book1.xlsx#Sheet2>`. However using this "uri" for the named graph will also not return any triples. 

My hunch is that there is a discrepancy in the different parts of the code that serialize and deserialize file paths, but my java is not good enough to find this issue myself.

**Comment by luigi-asprino** [comment]
Hi,
thanks for reporting this problem.
It is related to how the root argument is retrieved, since the graph URI is derived from the `root` argument.
Essentially, a URL object is created for keeping the location of the resources, but when this object is transformed into a string to mint the URI of the root, the underlying Java library returns URIs  ``file:/a.ext`` (instead of `file:///`).
This problem occurs only for local resources.

**Comment by luigi-asprino** [comment]
In https://github.com/SPARQL-Anything/sparql.anything/commit/e724f357cd9e33bf019e6837effaac494c86f3e6, instead of getting the root argument directly from the URL object, the location is encapsulated into a Path object via ``Path.of(url.toURI()).toUri()`` (only in the case that the location is a local file).

I've also refactored the method Triplifier.getRootArgument() (which was much more complicated than it should have been).
