### ISSUE TITLE
`whatwg:innerText` is duplicated several times

### ISSUE THREAD

**Issue by VladimirAlexiev** [SPARQL-Anything/sparql.anything#453]
(Related to https://github.com/SPARQL-Anything/sparql.anything/issues/452)
See the test files at https://gist.github.com/VladimirAlexiev/318ab4924c756ead618ebdded6428509.
`sparql-anything-test-html.ttl` was made using https://sparql-anything.readthedocs.io/en/latest/formats/HTML/:

`innerText` repeats the same text twice:
```ttl
@prefix html:  <https://html.spec.whatwg.org/#>.

html:innerHTML  "<plu:indicationreference>\n plot_coverage\n</plu:indicationreference>\n<plu:value uom=\"m2\">\n 869.0\n</plu:value>" ;
html:innerText  "plot_coverage 869.0 plot_coverage 869.0"
```

The number of duplicates seems to depend on the level of nesting, eg in another spot the text is in triplicate:
```ttl
html:innerHTML  "<plu:dimensioningindicationintegervalue>\n <plu:indicationreference>\n  full_storeys\n </plu:indicationreference>\n <plu:value>\n  6\n </plu:value> \n</plu:dimensioningindicationintegervalue>" ;
html:innerText  "full_storeys 6 full_storeys 6 full_storeys 6"
```

**Comment by luigi-asprino** [comment]
Hi,

thanks for reporting this. 

It is due to this
https://github.com/SPARQL-Anything/sparql.anything/blob/9b7505424e918c3273c17d9f4b7538e93e61af84/sparql-anything-html/src/main/java/io/github/sparqlanything/html/HTMLTriplifier.java#L191

`element.select("*")` takes the current element and its descendants recursively.
This is probably to attach some text to an element even if it is in one of its descendants.

A solution could be

```java
 String innerText = element.text(); 
```

but this attaches the text to the resource referring to the element which directly contains the text.

**Comment by enridaga** [comment]
> but this attaches the text to the resource referring to the element which directly contains the text.

I think this is the expected behaviour, right?
