### ISSUE TITLE
Add link/badge to Community Survey: "How to join"

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#480]
As the summary says

**Comment by luigi-asprino** [comment]
I think this can be closed as I can see the badge

**Comment by justin2004** [comment]
hey @luigi-asprino @enridaga ,
speaking of the sparql anything community...

what do you guys think about making some vinyl stickers to pass around? i have a [visidata](https://github.com/saulpw/visidata) decal on my water bottle and because of it i've had several conversations with people about the tool. i'd chip in on the run of stickers if we think it is worth doing.
