### ISSUE TITLE
sparql.anything.parser won't automatically build on Eclipse 4

### ISSUE THREAD

**Issue by alexdma** [SPARQL-Anything/sparql.anything#57]
When building the entire project on 

    Eclipse 2020-12 (4.18.0) with embedded Maven 3.6.3 runtime
    OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)

`sparql.anything.parser` throws Java build errors due to not being able to find the parser/lexer classes generated by antlr.

M2E recognises the `target/generated-sources/antlr4` folder as a source folder, however the .java files in there are not being placed in directories that follow the expected package structure, but dropped in that folder altogether. For some reason, this doesn't seem to cause a problem when building from the command line.

Steps I took to solve it (which seems to preserve a clean cmdline Maven build):
1. moved `sparql.anything.parser/src/main/antlr4/FacadeIRI.g4` to `sparql.anything.parser/src/main/antlr4/com/github/spiceh2020/sparql/anything/facadeiri/antlr/FacadeIRI.g4`
2. Removed package declaration from `@header` in `FacadeIRI.g4`

**Comment by enridaga** [comment]
Maybe we can add options for specify headers to be used in the HTTP connection, for example: `http.header.accept`, `http.header.cache-control`, ... This may also include adding authentication credentials. However, this requires developing a class for HTTP related operations so that all triplifiers can benefit from it. In general, content retrieval is in most cases independent from the format (until we focus on things other than files)

**Comment by luigi-asprino** [comment]
@alexdma , thanks a lot for the suggestion!

**Comment by luigi-asprino** [comment]
Closed via 0ef15c9
