### ISSUE TITLE
Use media-type property as HTTP Accept header?

### ISSUE THREAD

**Issue by alexdma** [SPARQL-Anything/sparql.anything#58]
If I wanted to use SPARQL-Anything as a proxy to an existing HTTP API, the latter does not usually provide something like a filename extension to guess the content type.

Since there is a property `media-type` that is used internally to select the triplifier, could it also be sent as an Accept header in the HTTP request being proxied?

Say, for an ORCID (pretending it didn't have an RDF API), I would do

    SERVICE <x-sparql-anything:location=https://orcid.org/0000-XXXX-XXXX-XXXX,media-type=application/json>

At the moment, the response still returns HTML and will not be parsed, which forces me to require the HTML triplifier.

**Comment by enridaga** [comment]
Maybe we can add options for specify headers to be used in the HTTP connection, for example: `http.header.accept`, `http.header.cache-control`, ... This may also include adding authentication credentials. However, this requires developing a class for HTTP related operations so that all triplifiers can benefit from it. In general, content retrieval is in most cases independent from the format (until we focus on things other than files)

**Comment by alexdma** [comment]
Indeed, the next thing I was going to propose was support for HTTP authentication - the data API in my use case is behind one

**Comment by enridaga** [comment]
This also relates to #66

**Comment by enridaga** [comment]
It is now possible to specify an accept header, after #67 

I think reusing the media-type property can also be an option but less robust than adding a specific one. I am incline to close this one, unless others believe there is a value in implementing this.

**Comment by justin2004** [comment]
yeah this i think is what @alexdma wants:

> SERVICE <x-sparql-anything:location=https://orcid.org/0000-XXXX-XXXX-XXXX,media-type=application/json,http.header.Accept=application/json>
