### ISSUE TITLE
service silent

### ISSUE THREAD

**Issue by justin2004** [SPARQL-Anything/sparql.anything#63]
> The SILENT keyword indicates that errors encountered while accessing a remote SPARQL endpoint should be ignored while processing the query.

https://www.w3.org/TR/2013/REC-sparql11-federated-query-20130321/#service

```
curl --silent  -H 'Accept: text/csv' 'http://localhost:3000/sparql.anything'  \
--data-urlencode 'query=
PREFIX xyz: <http://sparql.xyz/facade-x/data/>
PREFIX ns: <http://sparql.xyz/facade-x/ns/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix xhtml: <http://www.w3.org/1999/xhtml#> 
SELECT *
WHERE {
{
    service silent <x-sparql-anything:file:///mnt/does_not_exist.txt> {
        ?s ?p ?o .
}
}
union
{
    service <x-sparql-anything:https://gist.githubusercontent.com/justin2004/edaaef0137f1c066c88d2c0b43adc254/raw/7d2852cfaef082fb923717b9f22b3b34ca157780/sample.csv> {
        ?s ?p ?o
}
}
}'
```

returns:
```
Error 500: null
```

**Comment by luigi-asprino** [comment]
It seems that service silent doesn't work as expected when the execution is delegated to execute(OpBGP,QueryIterator)
In fact, the keyword is provided at service level, but it is not propagated if the execution is delegated to execute(OpBGP,QueryIterator). This could occur in case the BGP contains magic properties (e.g. fx:anySlot).
This has not created any problems so far because the exception  is not re-thrown  [here](https://github.com/SPARQL-Anything/sparql.anything/blob/35ac75a13675e8426fa26997c95f95cd354fdcb2/sparql-anything-engine/src/main/java/com/github/sparqlanything/engine/FacadeXOpExecutor.java#L242)
BTW [this line](https://github.com/SPARQL-Anything/sparql.anything/blob/35ac75a13675e8426fa26997c95f95cd354fdcb2/sparql-anything-engine/src/test/java/com/github/sparqlanything/engine/test/TestSilent.java#L58) should be deleted.

**Comment by luigi-asprino** [comment]
With [b10ae5d](https://github.com/SPARQL-Anything/sparql.anything/commit/b10ae5dcd6e8367a93fbb1b4c7ebcc221951bf22) FacadeXExecutionContext has a silent field which is set as true in the case that the SILENT keyword is provided. 
The field is then used in the execution of the BGP.
