### ISSUE TITLE
Is fx:anySlot equivalent to rdfs:member already available in Jena?

### ISSUE THREAD

**Issue by enridaga** [SPARQL-Anything/sparql.anything#77]
AnySlot matches all container membership properties, it looks like this is the same as the rdfs:member. Tests needed.

**Comment by luigi-asprino** [comment]
It is not and can't be since magic properties doesn't work within service clause and that's perfectly makes sense since the SERVICE operator is executed by an external query engine.
fx:anySlot wasn't implemented as standard Jena's magic property, but required a proper handling of the BGP instead.
I think that this can be closed
